### ISSUE TITLE
table with role="cell"

### ISSUE THREAD

**Issue by Watso196** [jsx-eslint/eslint-plugin-jsx-a11y#998] opened 2024-07-30 21:24 UTC

**Comment by ljharb** [comment] 2024-07-30 21:27
I have no idea what your issue is; can you elaborate?

**Comment by ljharb** [comment] 2024-07-30 21:33
Duplicate of #999, I presume.

**Closed as not planned by ljharb** 2024-07-30 21:33 UTC
Labels: invalid

**Comment by Watso196** [comment] 2024-07-30 21:37
Yes @ljharb my apologies! I didn't realize I accidentally submitted this.
