### ISSUE TITLE
label-has-associated-control regression

### ISSUE THREAD

**Issue by EvgenyOrekhov** [jsx-eslint/eslint-plugin-jsx-a11y#962] opened 2023-11-07 16:26 UTC
Looks like `controlComponents` option is no longer respected.

The following code now gives `A form label must be associated with a control` warning:

```jsx
/* eslint
  "jsx-a11y/label-has-associated-control": [
    "error", { "controlComponents": ["InputComponent"] },
  ],
*/

function MyComponent() {
  return (
    <label>
      My label
      <InputComponent />
    </label>
  );
}
```

Started happening after upgrade from 6.7.1 to 6.8.0.

**Comment by lb-** [comment] 2024-10-22 23:32
I have been unable to reproduce this issue, testing against the latest released version `6.10.1` (example code below).

It's possible this was fixed by a08fbcc502d6a6fa7d01a48c5f0b895c61e8cdd5 / #1004

Nonetheless, I might put up a PR that adds extra test coverage for this area for non-nested usage.

```jsx
/* eslint
  "jsx-a11y/label-has-associated-control": [
    "error", { "controlComponents": ["InputComponent"] },
  ],
*/

const InputComponents = () => <input />;

function MyComponent() {
  return (
    <label>
      My label
      <InputComponents />
    </label>
  );
}

export default MyComponent;

```

**Closed** 2024-10-25 21:57 UTC
Labels: bug, help wanted
