### ISSUE TITLE
Release 6.x.x

### ISSUE THREAD

**Issue by vaseker** [jsx-eslint/eslint-plugin-jsx-a11y#842] opened 2022-03-16 08:07 UTC
Hello!

Is it possible to release actual codebase?

Reason: current main branch contain useful configuration option `allowedInvalidRoles` for `aria-role` rule.

Thank you.

**Comment by ljharb** [comment] 2022-03-16 16:14
Duplicate of #797.

**Closed by ljharb** 2022-03-16 16:14 UTC
