### ISSUE TITLE
jsx-a11y/control-has-associated-label triggers on TD element

### ISSUE THREAD

**Issue by curtvict** [jsx-eslint/eslint-plugin-jsx-a11y#967] opened 2023-11-14 18:02 UTC
This doesn't seem right, does it?

![image](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/assets/96080054/1b74811e-0d88-4da8-aba0-92d037647e69)

Here's all the eslint entries from my package.json:

```
    "@typescript-eslint/eslint-plugin": "6.9.1",
    "@typescript-eslint/parser": "6.9.1",
    "eslint": "8.53.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "17.1.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-formatter-summary": "1.1.0",
    "eslint-import-resolver-typescript": "3.6.1",
    "eslint-plugin-import": "2.29.0",
    "eslint-plugin-jest": "27.6.0",
    "eslint-plugin-jsx-a11y": "6.8.0",
    "eslint-plugin-mdx": "2.2.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.33.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-storybook": "0.6.15",
```

**Comment by ljharb** [comment] 2023-11-14 18:19
It's not; duplicate of #959.

**Closed by ljharb** 2023-11-14 18:19 UTC
