### ISSUE TITLE
TypeError: (0 , _minimatch.default) is not a function

### ISSUE THREAD

**Issue by semihraifgurel** [jsx-eslint/eslint-plugin-jsx-a11y#929] opened 2023-04-11 15:38 UTC
```
TypeError: (0 , _minimatch.default) is not a function
Occurred while linting /Users/user/project/src/components/Search.tsx:64
Rule: "jsx-a11y/label-has-associated-control"

TypeError: (0 , _minimatch.default) is not a function
Occurred while linting /Users/user/project/src/components/Search.tsx:64
Rule: "jsx-a11y/label-has-associated-control"
    at traverseChildren (/Users/user/project/node_modules/eslint-plugin-jsx-a11y/lib/util/mayContainChildComponent.js:38:102)
    at mayContainChildComponent (/Users/user/project/node_modules/eslint-plugin-jsx-a11y/lib/util/mayContainChildComponent.js:48:10)
    at /Users/user/project/node_modules/eslint-plugin-jsx-a11y/lib/rules/label-has-associated-control.js:69:57
    at Array.some (<anonymous>)
    at rule (/Users/user/project/node_modules/eslint-plugin-jsx-a11y/lib/rules/label-has-associated-control.js:68:48)
    at ruleErrorHandler (/Users/user/project/node_modules/eslint/lib/linter/linter.js:1077:28)
    at /Users/user/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/user/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/user/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
Process finished with exit code -1
```

```json
"rules": {
	"jsx-a11y/label-has-associated-control": [
		2,
		{
			"labelComponents": ["Label"],
			"labelAttributes": ["label"],
			"controlComponents": ["Input", "Search"],
			"depth": 3
		}
	],
}
```
`"eslint": "^8.38.0",`

```jsx
const Search = () => {
	return (
		<div className='d-flex' data-tour='search'>
			<label className='border-0 bg-transparent cursor-pointer' htmlFor='searchInput'>
				<Icon icon='Search' size='2x' color='primary' />
			</label>
			<Input
				id='searchInput'
				type='search'
				className='border-0 shadow-none bg-transparent'
				placeholder='Search...'
				onChange={formik.handleChange}
				value={formik.values.searchInput}
				autoComplete='off'
			/>
		</div>
	)
};
```

**Comment by ljharb** [comment] 2023-04-11 15:54
Seems like a bug in minimatch. What version do you have installed?

**Comment by semihraifgurel** [comment] 2023-04-11 15:58
`"eslint-plugin-jsx-a11y": "^6.7.1",`

**Comment by ljharb** [comment] 2023-04-11 16:02
I asked about minimatch.

**Comment by poshiemaaat** [comment] 2024-01-10 15:43
Was this ever solved? minimatch isn't a direct dependency of ours but I can see it's using `3.1.2`.

**Comment by ljharb** [comment] 2024-01-10 17:18
@poshiemaaat no, but thanks that helps. what is `typeof require('minimatch')` in the repl?

**Comment by poshiemaaat** [comment] 2024-01-10 19:25
@ljharb I'm not sure how to do that, actually. I can't seem to reproduce this at all locally; it's just failing in our pipeline. I have identical files locally to the best of my knowledge. I'm not sure how to "monkey-patch" the node_modules file in the pipeline to get the value of `typeof require('minimatch')` here.

**Comment by poshiemaaat** [comment] 2024-01-10 19:27
Pipeline is running node 20.10.0, ubuntu:22.04 btw!

**Comment by poshiemaaat** [comment] 2024-01-10 19:52
I GOT IT

Run a `npm dedupe` to force the minimatch package to get upgraded to v9.x. Pipeline was happy now. Oh my goodness.

**Comment by poshiemaaat** [comment] 2024-01-10 19:53
Oh and you can see the list of minimatch packages installed due to all the dependency tree by running `npm ls minimatch`. Thank me later.

**Comment by ljharb** [comment] 2024-01-10 19:54
`npm explain minimatch` should give you more helpful output.

we require minimatch v3 here, so using v9 i would expect to break things :-/

**Comment by poshiemaaat** [comment] 2024-01-11 00:43
Oooooh good point. I must have missed something too because I now see `3.1.2` again, but the pipeline is happy. Soooooooooooooooo 🤫 don't spook the pipeline.

**Comment by ljharb** [comment] 2024-01-11 01:03
Given that @semihraifgurel hasn't replied; yarn is known to be broken; and your issue was resolved, I'm going to close this, but will be happy to reopen if needed.

**Closed by ljharb** 2024-01-11 01:03 UTC
