### ISSUE TITLE
label-has-associated-control does not work with solidjs when using the `for` attribute

### ISSUE THREAD

**Issue by alightgoesout** [jsx-eslint/eslint-plugin-jsx-a11y#922] opened 2023-02-03 17:24 UTC
Contrary to React, solidjs uses the standard html attributes (e.g., `class` not `className`), and so the label attribute used to specify the control is `for`, not `htmlFor`. As is, I cannot use the rule.

Maybe we could specify the name of the attribute in an option?

**Comment by ljharb** [comment] 2023-02-03 17:31
I think this is a duplicate of #894?

**Comment by alightgoesout** [comment] 2023-02-03 17:35
Indeed, I had not seen it.

**Closed** 2023-02-03 17:47 UTC
