### ISSUE TITLE
label-has-associated-control error

### ISSUE THREAD

**Issue by whtjs** [jsx-eslint/eslint-plugin-jsx-a11y#931] opened 2023-05-16 02:36 UTC
<img width="1048" alt="image" src="https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/assets/22754824/a204c9af-c5ed-44af-beee-8f6a91a88d3e">

i have followed example code that link provide [(label-has-associated-control)](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md)

but it still making lint error. i think there is some issue

**Comment by ljharb** [comment] 2023-05-16 04:40
The issue is likely that you *also* need a for/id relationship between the label and the input; nesting isn't sufficient.

**Comment by whtjs** [comment] 2023-05-16 05:54
oh so you mean nesting case may can solve some problem but not in my case?

**Comment by ljharb** [comment] 2023-05-16 06:08
No, I mean that the rule can be configured three ways: nesting only, ID linking only, or both. To be truly accessible, "both" is always required.

**Comment by whtjs** [comment] 2023-05-16 06:15
oh than i have to try change my `.eslintrc`

**Comment by ljharb** [comment] 2023-05-16 06:17
That's one path, but then you're not being fully accessible - some devices only work with nesting, some only with linking, so you must do both to match the spirit of this rule, and to be fully inclusive.

Closing, since it's answered.

**Closed by ljharb** 2023-05-16 06:17 UTC
