### ISSUE TITLE
Eslint "control-has-associated-label" error on non-label tag

### ISSUE THREAD

**Issue by ashtonisher** [jsx-eslint/eslint-plugin-jsx-a11y#996] opened 2024-07-11 03:05 UTC
#Inappropriate eslint error

There's no <label> tag in this component, only `table` & `div` elements.
But i got eslint error on `th` tag, which is, "A control must be associated with a text label.eslint[jsx-a11y/control-has-associated-label]"

I think this comes from "&nbsp;"part, but i have to use &nbsp; or empty space '  ' in `th`tag cause of layout. 
And also there's no `label` in this code!

Is this bug ? or can i fix this?
- `MyComponent.tsx`

```typescript
<table>
      <thead>
          <tr>
              <th>&nbsp;</th> /* no content. just for table layout */
              <th>content</th>
              <th>price</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>
                <img src="icon.png" alt="" />
              </td>
              <td>content1</td>
              <td>content2</td>
          </tr>
     </tbody>
</table>
```

- `.eslintrc.js` (in monorepo)
```js
module.exports = {
 rules: {
    'no-console': 'off',
    'no-plusplus': 'off',
    'import/no-duplicates': 'off',
    'import/prefer-default-export': 'off',
    'react/prop-types': 'off',
    'react/destructuring-assignment': 'off',
    'react/require-default-props': 'off',
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-props-no-spreading': 'off',
    'no-underscore-dangle': 'off',
    'guard-for-in': 'off',
    'react/function-component-definition': ['error', { namedComponents: ['arrow-function', 'function-declaration'] }],
    'no-restricted-syntax': ['error', 'LabeledStatement', 'WithStatement'],
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
    '@typescript-eslint/naming-convention': [
      'error',
      {
        selector: 'variable',
        format: ['camelCase', 'UPPER_CASE', 'PascalCase', 'snake_case'],
        leadingUnderscore: 'allow',
      },
    ],
    '@typescript-eslint/no-use-before-define': 'off',
    'jsx-a11y/label-has-associated-control': [
      'error',
      {
        labelAttributes: ['htmlFor'],
      },
    ],
    'jsx-a11y/media-has-caption': 'off',
    'no-param-reassign': 'off',
    'no-return-assign': 'off', 
    'react/no-array-index-key': 'off', 
    'arrow-body-style': 'off',
    'react/jsx-pascal-case': 'off',
    'no-alert': 'off',
    'consistent-return': 'off',
    'react/no-unescaped-entities': [2, { forbid: ['>', '}'] }],
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: ['./tsconfig.json', './packages/**/tsconfig.json', './apps/**/tsconfig.json'],
    createDefaultProgram: true,
  },
...
```

**Comment by ljharb** [comment] 2024-07-11 05:24
This is a duplicate of #959. When I take a look at it, I'll include your repro code.

**Closed as not planned by ljharb** 2024-07-11 05:24 UTC
