### ISSUE TITLE
add support for eslint 7

### ISSUE THREAD

**Issue by JustFly1984** [jsx-eslint/eslint-plugin-jsx-a11y#703] opened 2020-06-18 09:38 UTC
I'me getting warning in ci/cd logs on yarn install output. We have latest eslint 7.2.0, and it seems work fine in general
```bash
warning " > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
```

**Comment by ljharb** [comment] 2020-06-18 17:53
Duplicate of #683.

**Closed by ljharb** 2020-06-18 17:53 UTC
